import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Layout Auth",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>{children}</div>
  );
}
